#!/bin/bash
# Guide: Change Apps Script GCP Project to Enable API Deployment

echo "🔧 OPTION A: Link Apps Script to Service Account's Project"
echo "============================================================"
echo ""
echo "📋 Current State:"
echo "   Apps Script GCP Project: jibber-jabber-knowledge (1090450657636)"
echo "   Service Account Project: inner-cinema-476211-u9 (922809339325)"
echo "   Status: ❌ Different projects = No API access"
echo ""
echo "📋 Target State:"
echo "   Apps Script GCP Project: inner-cinema-476211-u9 (922809339325)"
echo "   Service Account Project: inner-cinema-476211-u9 (922809339325)"
echo "   Status: ✅ Same project = Automatic API access"
echo ""
echo "============================================================"
echo "STEP-BY-STEP INSTRUCTIONS"
echo "============================================================"
echo ""
echo "I've opened the Apps Script Settings page for you."
echo "Now follow these steps:"
echo ""
echo "1️⃣  Find the section: 'Google Cloud Platform (GCP) project'"
echo "    Current value shows: 1090450657636"
echo ""
echo "2️⃣  Click: 'Change project' button"
echo ""
echo "3️⃣  A dialog will appear with two steps:"
echo ""
echo "    Step 1: Instructions (just read them)"
echo "    Step 2: Enter project number"
echo ""
echo "4️⃣  In Step 2, enter this number:"
echo ""
echo "    ┌─────────────────────────────────────┐"
echo "    │  922809339325                       │"
echo "    └─────────────────────────────────────┘"
echo ""
echo "5️⃣  You'll see a warning message:"
echo "    '⚠️  All user authentications for your old project will be"
echo "     permanently revoked.'"
echo ""
echo "    This is NORMAL and EXPECTED. Click 'Set project' anyway."
echo ""
echo "6️⃣  The page will refresh and show:"
echo "    GCP Project: 922809339325"
echo ""
echo "============================================================"
echo "WHAT THIS DOES"
echo "============================================================"
echo ""
echo "✅ Links Apps Script to inner-cinema-476211-u9"
echo "✅ Grants service account automatic access"
echo "✅ Enables Apps Script API deployment"
echo "✅ Connects to your BigQuery data (same project)"
echo ""
echo "⚠️  Will revoke existing OAuth tokens (you'll re-authorize)"
echo "⚠️  Can't revert to jibber-jabber-knowledge (permanent change)"
echo ""
echo "============================================================"
echo "AFTER CHANGING THE PROJECT"
echo "============================================================"
echo ""
echo "Once you've entered 922809339325 and clicked 'Set project':"
echo ""
echo "1. Wait 30 seconds for changes to propagate"
echo ""
echo "2. Run this command:"
echo "   python3 update_existing_script.py"
echo ""
echo "3. You should see:"
echo "   ✅ Successfully updated script content!"
echo "   🔗 Links to your sheet and script"
echo ""
echo "4. Refresh your Google Sheet (Cmd+R)"
echo ""
echo "5. Look for menu: ⚡ Power Market"
echo ""
echo "6. Click: ⚡ Power Market → 🚀 One-Click Setup"
echo ""
echo "7. Authorize when prompted (one-time)"
echo ""
echo "8. Done! Dashboard will auto-refresh every 5 minutes"
echo ""
echo "============================================================"
echo "READY TO PROCEED?"
echo "============================================================"
echo ""
echo "Go to the Apps Script Settings page and:"
echo "  • Click 'Change project'"
echo "  • Enter: 922809339325"
echo "  • Click 'Set project'"
echo ""
echo "Then run: python3 update_existing_script.py"
echo ""
