#!/bin/bash
# clasp_login_via_ssh.sh
# Login to Clasp from Dell server via SSH tunnel

set -e

echo "═══════════════════════════════════════════════════════════"
echo "  Clasp Login via SSH Port Forwarding"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "This script helps you authenticate Clasp on the Dell server"
echo "when connecting via SSH from your Mac."
echo ""
echo "SETUP INSTRUCTIONS:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "On your iMac (LOCAL machine), run these commands:"
echo ""
echo "1. Open a NEW terminal window (not this SSH session)"
echo ""
echo "2. Create SSH tunnel for OAuth callback:"
echo ""
echo "   ssh -L 8888:localhost:8888 george@<DELL_IP_ADDRESS>"
echo ""
echo "   Replace <DELL_IP_ADDRESS> with your Dell's IP"
echo ""
echo "3. In that SSH session, run:"
echo ""
echo "   cd /home/george/GB-Power-Market-JJ"
echo "   clasp login"
echo ""
echo "4. Copy the URL that appears and paste in your iMac browser"
echo ""
echo "5. Login with: george@upowerenergy.uk"
echo ""
echo "6. After authorization, you'll be redirected to localhost:8888"
echo "   - The SSH tunnel will forward this to Dell"
echo "   - Clasp will receive the token"
echo "   - Authentication complete!"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "ALTERNATIVE: Use --no-localhost flag"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "If SSH tunnel doesn't work, try:"
echo ""
echo "   clasp login --no-localhost"
echo ""
echo "This will:"
echo "1. Give you an authorization URL"
echo "2. Open it in your iMac browser"
echo "3. After login, you'll get an authorization CODE"
echo "4. Paste that code back in the terminal"
echo "5. Done!"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

read -p "Press Enter to try 'clasp login --no-localhost' now..."

clasp login --no-localhost
