#!/bin/bash
# Simple Apps Script V2 Deployment Guide

SPREADSHEET_ID="1LmMq4OEE639Y-XXpOJ3xnvpAmHB6vUovh5g6gaU_vzc"

echo "================================================================================"
echo "📜 APPS SCRIPT V2 - DEPLOYMENT GUIDE"
echo "================================================================================"
echo ""
echo "The easiest way to deploy Apps Script is through the Google Sheets UI."
echo ""
echo "================================================================================"
echo "📋 COPY THE CODE (STEP 1)"
echo "================================================================================"
echo ""
echo "The code you need is in: apps_script_v2.gs"
echo ""
echo "Opening it now for you to copy..."
echo ""

# Open the file
if command -v code &> /dev/null; then
    code apps_script_v2.gs
    echo "✅ Opened in VS Code"
elif command -v open &> /dev/null; then
    open -a "TextEdit" apps_script_v2.gs
    echo "✅ Opened in TextEdit"
else
    cat apps_script_v2.gs
fi

echo ""
echo "================================================================================"
echo "📝 PASTE INTO GOOGLE SHEETS (STEP 2)"
echo "================================================================================"
echo ""
echo "1. Open your spreadsheet:"
echo "   https://docs.google.com/spreadsheets/d/$SPREADSHEET_ID/"
echo ""
echo "2. Click: Extensions → Apps Script"
echo ""
echo "3. In the Apps Script editor:"
echo "   • You'll see Code.gs already open"
echo "   • Select ALL existing content (Cmd+A)"
echo "   • DELETE it"
echo "   • PASTE the contents from apps_script_v2.gs"
echo "   • Click Save (💾 icon or Cmd+S)"
echo ""
echo "4. Close the Apps Script tab"
echo ""
echo "5. Return to your spreadsheet and REFRESH the page"
echo ""
echo "6. Look for the new menu: 🚀 Dashboard V2"
echo ""
echo "================================================================================"
echo "✅ TESTING THE MENU (STEP 3)"
echo "================================================================================"
echo ""
echo "After refreshing, you should see '🚀 Dashboard V2' in the menu bar."
echo ""
echo "Click it and try:"
echo "  • 📋 Rebuild V2 Dropdowns - Sets up dropdown validation"
echo "  • 🎨 Apply V2 Theme - Applies orange/blue theme"
echo "  • 🔄 Refresh All V2 Data - Updates all V2 sheets"
echo ""
echo "================================================================================"
echo "🔧 ALTERNATIVE: Use clasp (Advanced)"
echo "================================================================================"
echo ""
echo "If you prefer command-line deployment with clasp:"
echo ""
echo "1. Get your spreadsheet's script ID:"
echo "   • Open: https://docs.google.com/spreadsheets/d/$SPREADSHEET_ID/"
echo "   • Extensions → Apps Script"
echo "   • In URL bar, copy the ID between /d/ and /edit"
echo "   • Example: ...script.google.com/d/SCRIPT_ID_HERE/edit"
echo ""
echo "2. Update .clasp.json:"
echo "   cd apps-script-v2"
echo '   echo {"scriptId":"YOUR_SCRIPT_ID","rootDir":"."} > .clasp.json'
echo ""
echo "3. Push the code:"
echo "   clasp push"
echo ""
echo "================================================================================"
echo ""
echo "Need help? The manual method (copy/paste) takes 60 seconds and just works!"
echo ""
