#!/bin/bash
# Quick Deploy DNO Map to Google Sheets

echo "🗺️ DNO MAP DEPLOYMENT"
echo "===================="
echo ""
echo "✅ Code.gs is ready at: /home/george/GB-Power-Market-JJ/Code.gs"
echo ""
echo "📋 DEPLOY STEPS (2 minutes):"
echo ""
echo "1. Open spreadsheet:"
echo "   https://docs.google.com/spreadsheets/d/1MSl8fJ0to6Y08enXA2oysd8wvNUVm3AtfJ1bVqRH8_I/"
echo ""
echo "2. Click: Extensions → Apps Script"
echo ""
echo "3. DELETE all existing code in the editor"
echo ""
echo "4. COPY the code below and PASTE into Apps Script editor:"
echo ""
echo "----------------------------------------"
cat /home/george/GB-Power-Market-JJ/Code.gs
echo "----------------------------------------"
echo ""
echo "5. Click Save (💾) then close Apps Script tab"
echo ""
echo "6. REFRESH the spreadsheet"
echo ""
echo "7. You'll see '🗺️ DNO Map' menu at top"
echo ""
echo "8. Click: 🗺️ DNO Map → View Interactive Map"
echo ""
echo "✅ DONE! You'll see real UK DNO boundaries with:"
echo "   - All 14 license areas"
echo "   - Real geographic shapes (not fake rectangles)"
echo "   - Interactive hover/click"
echo "   - Data from 5.6MB GeoJSON file"
echo ""
