#!/usr/bin/env python3
"""
DNO DUoS Data Excel Workbook Generator
--------------------------------------
Creates a simple Excel workbook from the CSV files generated by the generate_duos_csv_files.py script.
"""

import os
from datetime import datetime

import pandas as pd


class DNODuosExcelGenerator:
    def __init__(self):
        """Initialize the generator."""
        self.output_dir = "duos_outputs2"
        self.csv_files = {
            "reference": os.path.join(self.output_dir, "DNO_Reference.csv"),
            "summary": os.path.join(self.output_dir, "DNO_DUoS_Summary.csv"),
            "band_stats": os.path.join(self.output_dir, "DNO_DUoS_Band_Stats.csv"),
            "all_data": os.path.join(self.output_dir, "DNO_DUoS_All_Data.csv"),
        }

        # Year-specific CSVs
        self.year_dir = os.path.join(self.output_dir, "by_year")
        self.year_csv_files = {}
        if os.path.exists(self.year_dir):
            for file in os.listdir(self.year_dir):
                if file.endswith(".csv") and file.startswith("Year_"):
                    year = file.replace("Year_", "").replace(".csv", "")
                    self.year_csv_files[year] = os.path.join(self.year_dir, file)

        # DNO-specific CSVs
        self.dno_dir = os.path.join(self.output_dir, "by_dno")
        self.dno_csv_files = {}
        if os.path.exists(self.dno_dir):
            for file in os.listdir(self.dno_dir):
                if file.endswith(".csv"):
                    dno_name = file.replace(".csv", "")
                    self.dno_csv_files[dno_name] = os.path.join(self.dno_dir, file)

    def generate_excel(self):
        """Generate Excel workbook with all the data."""
        print("🚀 DNO DUoS DATA EXCEL GENERATOR")
        print("=============================")

        # Set up output file
        now = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_file = os.path.join(
            self.output_dir, f"DNO_DUoS_Complete_Data_{now}.xlsx"
        )

        print(f"📊 Creating Excel workbook: {output_file}")

        # Create a Pandas ExcelWriter object
        with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
            # Add reference data
            self._add_sheet_from_csv(
                writer, "DNO_Reference", self.csv_files["reference"]
            )

            # Add summary data
            self._add_sheet_from_csv(writer, "Summary", self.csv_files["summary"])

            # Add band statistics
            self._add_sheet_from_csv(
                writer, "Band_Statistics", self.csv_files["band_stats"]
            )

            # Add year-specific sheets
            for year, file_path in sorted(self.year_csv_files.items()):
                self._add_sheet_from_csv(writer, f"Year_{year}", file_path)

            # Add DNO-specific sheets (as many as will fit)
            for dno_name, file_path in sorted(self.dno_csv_files.items()):
                sheet_name = dno_name[:31]  # Excel limits sheet names to 31 characters
                self._add_sheet_from_csv(writer, sheet_name, file_path)

            # Add all data as the last sheet
            self._add_sheet_from_csv(writer, "All_Data", self.csv_files["all_data"])

        print(f"✅ Excel workbook created successfully: {output_file}")

        # Also create a separate workbook with just the reference and summary for quick viewing
        summary_file = os.path.join(self.output_dir, f"DNO_DUoS_Summary_{now}.xlsx")
        with pd.ExcelWriter(summary_file, engine="openpyxl") as writer:
            self._add_sheet_from_csv(
                writer, "DNO_Reference", self.csv_files["reference"]
            )
            self._add_sheet_from_csv(writer, "Summary", self.csv_files["summary"])
            self._add_sheet_from_csv(
                writer, "Band_Statistics", self.csv_files["band_stats"]
            )

        print(f"✅ Summary Excel workbook created successfully: {summary_file}")

    def _add_sheet_from_csv(self, writer, sheet_name, csv_path):
        """Add a sheet to the Excel workbook from a CSV file."""
        if not os.path.exists(csv_path):
            print(f"❌ CSV file not found: {csv_path}")
            return

        try:
            df = pd.read_csv(csv_path)
            df.to_excel(writer, sheet_name=sheet_name, index=False)
            print(f"  - Added sheet: {sheet_name}")
        except Exception as e:
            print(f"❌ Error adding sheet {sheet_name}: {str(e)}")


if __name__ == "__main__":
    generator = DNODuosExcelGenerator()
    generator.generate_excel()
