#!/bin/bash
# Find the correct GCP project associated with your Apps Script

echo "🔍 Finding Your Apps Script's GCP Project"
echo "=================================================="
echo ""
echo "The Apps Script belongs to: upowerenergy.uk"
echo "But the service account is in: inner-cinema-476211-u9 (922809339325)"
echo ""
echo "We need to find the GCP project for upowerenergy.uk"
echo ""
echo "=================================================="
echo "OPTION 1: Check Apps Script Project Settings"
echo "=================================================="
echo ""
echo "1. Open Apps Script Settings:"
echo "   https://script.google.com/home/projects/1MOwnQtDEMiXCYuaeR5JA4Avz_M-xYzu_iQ20pRLXdsHMTwo4qJ0Cn6wx/settings"
echo ""
echo "2. Look for 'Google Cloud Platform (GCP) project' section"
echo ""
echo "3. If it shows 'Default' or an Apps Script-managed project:"
echo "   - It means no custom GCP project is linked yet"
echo "   - This is the current state (explains the 403 error)"
echo ""
echo "4. Note what it currently shows (Default or a project number)"
echo ""
echo "=================================================="
echo "OPTION 2: Check Your GCP Projects"
echo "=================================================="
echo ""
echo "1. Go to: https://console.cloud.google.com"
echo ""
echo "2. Click the project dropdown at the top"
echo ""
echo "3. Look for projects associated with upowerenergy.uk"
echo ""
echo "4. Note the project number for the upowerenergy.uk project"
echo ""
echo "=================================================="
echo "SOLUTION: Link Apps Script to Service Account's Project"
echo "=================================================="
echo ""
echo "Since your service account is in 'inner-cinema-476211-u9',"
echo "we should link the Apps Script TO that project:"
echo ""
echo "1. In Apps Script Settings, under 'GCP project':"
echo "   Click 'Change project'"
echo ""
echo "2. Enter this project number:"
echo "   922809339325"
echo ""
echo "3. This will:"
echo "   ✅ Link Apps Script to the same GCP project as service account"
echo "   ✅ Grant automatic access (same project = same permissions)"
echo "   ✅ Enable Apps Script API deployment"
echo ""
echo "4. Click 'Set project' and confirm the warning"
echo ""
echo "5. Then run:"
echo "   python3 update_existing_script.py"
echo ""
echo "=================================================="
echo "Why This Works"
echo "=================================================="
echo ""
echo "When Apps Script and service account are in the SAME GCP project:"
echo "  ✅ Service account automatically has access"
echo "  ✅ No manual sharing needed"
echo "  ✅ Apps Script API works immediately"
echo ""
echo "Current state:"
echo "  ❌ Apps Script: Default project (or upowerenergy.uk project)"
echo "  ❌ Service account: inner-cinema-476211-u9 (922809339325)"
echo "  ❌ Different projects = permission denied"
echo ""
echo "After linking:"
echo "  ✅ Apps Script: inner-cinema-476211-u9 (922809339325)"
echo "  ✅ Service account: inner-cinema-476211-u9 (922809339325)"
echo "  ✅ Same project = automatic access"
echo ""
echo "=================================================="
echo "Next Step: Link the Project"
echo "=================================================="
echo ""
echo "Go to Apps Script Settings and enter: 922809339325"
echo ""
