#!/bin/bash
# Complete deployment commands for AlmaLinux server
# Run this after uploading the files

echo "=== GB Power Map - Deployment Commands ==="
echo ""
echo "Files uploaded successfully to: root@94.237.55.234:/root/"
echo ""
echo "Now run these commands:"
echo ""
echo "# Step 1: SSH into your AlmaLinux server"
echo "ssh root@94.237.55.234"
echo ""
echo "# Step 2: Extract the deployment package"
echo "unzip gb_power_map_deployment.zip"
echo "cd gb_power_map_deployment"
echo ""
echo "# Step 3: Run the deployment script"
echo "sudo ./deploy.sh"
echo ""
echo "# Step 4: Configure Google Cloud credentials"
echo "export GOOGLE_APPLICATION_CREDENTIALS=/root/credentials.json"
echo "echo 'export GOOGLE_APPLICATION_CREDENTIALS=/root/credentials.json' >> ~/.bashrc"
echo ""
echo "# Step 5: Generate the map for the first time"
echo "python3 /var/www/maps/scripts/auto_generate_map_linux.py"
echo ""
echo "# Step 6: Check if it worked"
echo "ls -lh /var/www/maps/gb_power_complete_map.html"
echo "curl -I http://localhost/gb_power_complete_map.html"
echo ""
echo "# Step 7: Open in your browser"
echo "# Visit: http://94.237.55.234/gb_power_complete_map.html"
echo ""
echo "=== Done! ==="
