#!/bin/bash
# Clear explanation of the project linking decision

echo "🔄 Apps Script GCP Project - Decision Guide"
echo "=================================================="
echo ""
echo "CURRENT STATE:"
echo "  📊 BigQuery Data: inner-cinema-476211-u9 (922809339325)"
echo "  🔐 Service Account: inner-cinema-476211-u9 (922809339325)"
echo "  📝 Apps Script: jibber-jabber-knowledge (1090450657636)"
echo "  ❌ MISMATCH = Permission denied"
echo ""
echo "=================================================="
echo "OPTION A: Link Apps Script to inner-cinema (EASY)"
echo "=================================================="
echo ""
echo "Change Apps Script project number to: 922809339325"
echo ""
echo "RESULT:"
echo "  ✅ Apps Script → inner-cinema-476211-u9 (922809339325)"
echo "  ✅ Service Account → inner-cinema-476211-u9 (922809339325)"
echo "  ✅ BigQuery Data → inner-cinema-476211-u9 (922809339325)"
echo "  ✅ ALL IN SAME PROJECT = Works automatically!"
echo ""
echo "Time: 30 seconds"
echo "Steps:"
echo "  1. Apps Script Settings → Change project"
echo "  2. Enter: 922809339325"
echo "  3. Click 'Set project'"
echo "  4. Run: python3 update_existing_script.py"
echo "  5. Done!"
echo ""
echo "=================================================="
echo "OPTION B: Create service account in jibber-jabber"
echo "=================================================="
echo ""
echo "Keep Apps Script project as: 1090450657636"
echo "Create new service account in: jibber-jabber-knowledge"
echo ""
echo "REQUIRED STEPS:"
echo "  1. Go to https://console.cloud.google.com/iam-admin/serviceaccounts?project=jibber-jabber-knowledge"
echo "  2. Create new service account"
echo "  3. Download new credentials JSON"
echo "  4. Enable Apps Script API in jibber-jabber-knowledge"
echo "  5. Enable BigQuery API in jibber-jabber-knowledge"
echo "  6. Grant BigQuery permissions"
echo "  7. Update all scripts to use new credentials"
echo "  8. Test everything"
echo ""
echo "Time: 15-30 minutes"
echo "Complexity: High"
echo ""
echo "=================================================="
echo "RECOMMENDATION"
echo "=================================================="
echo ""
echo "✅ USE OPTION A (Change Apps Script project)"
echo ""
echo "Why:"
echo "  • Takes 30 seconds vs 30 minutes"
echo "  • Everything already set up in inner-cinema"
echo "  • No risk of breaking existing BigQuery access"
echo "  • All your data is already there"
echo "  • Service account already has all permissions"
echo ""
echo "The Apps Script doesn't care which project it's in."
echo "What matters is that it matches your service account!"
echo ""
echo "=================================================="
echo "ACTION NEEDED"
echo "=================================================="
echo ""
echo "In Apps Script Settings:"
echo "  Change project number from: 1090450657636"
echo "  To: 922809339325"
echo ""
echo "Then run:"
echo "  python3 update_existing_script.py"
echo ""
echo "✅ That's it!"
echo ""
