#!/bin/bash
# Quick Start Guide - Data Ingestion Todos

echo "======================================================================"
echo "GB Power Market JJ - Data Ingestion Quick Start"
echo "======================================================================"
echo ""
echo "📊 Current Status:"
echo "  P114 Backfill: 158.6M / 584M records (27.2%)"
echo "  Data Coverage: 22/46 sources (48%)"
echo "  Target Completion: 5-10 January 2026"
echo ""
echo "======================================================================"
echo "TODO 1: Monitor P114 Backfill (RUNNING)"
echo "======================================================================"
echo "✅ Worker active (PID 2275533, processing 2024-07-08 to 2024-07-14 R3)"
echo ""
echo "Check status:"
echo "  ps aux | grep ingest_p114"
echo ""
echo "Check progress:"
echo "  python3 -c \"
from google.cloud import bigquery
client = bigquery.Client(project='inner-cinema-476211-u9', location='US')
query = 'SELECT COUNT(*) as total FROM \\\`inner-cinema-476211-u9.uk_energy_prod.elexon_p114_s0142_bpi\\\`'
result = client.query(query).to_dataframe()
print(f'P114 Records: {result[\\\"total\\\"][0]:,} / 584,000,000 ({result[\\\"total\\\"][0]/584000000*100:.1f}%)')
\""
echo ""
echo "======================================================================"
echo "TODO 2: Download NESO Constraint Costs (MANUAL - START NOW)"
echo "======================================================================"
echo "⚠️  Manual download required (3-4 hours)"
echo ""
echo "Instructions: ~/GB-Power-Market-JJ/neso_downloads/DOWNLOAD_INSTRUCTIONS.md"
echo ""
echo "Quick summary:"
echo "  1. Constraint Breakdown: https://data.nationalgrideso.com/constraint-management/historic-constraint-breakdown"
echo "  2. MBSS: https://data.nationalgrideso.com/balancing-services/mbss-mandatory-balancing-services-costs"
echo "  3. Annual Reports: https://www.nationalgrideso.com/document/series/balancing-services-reports"
echo "  4. 24-Month Forecast: https://data.nationalgrideso.com/constraint-management/24-month-constraint-cost-forecast"
echo "  5. Modelled Costs: https://data.nationalgrideso.com/constraint-management/modelled-constraint-costs"
echo "  6. Skip Rates: https://data.nationalgrideso.com/balancing-services/skip-rate"
echo ""
echo "Save to: ~/GB-Power-Market-JJ/neso_downloads/constraint_costs/"
echo ""
echo "======================================================================"
echo "TODO 3: Ingest NESO Costs (AFTER TODO 2)"
echo "======================================================================"
echo "✅ Script ready: ingest_neso_constraint_costs.py"
echo ""
echo "Test ingestion (no upload):"
echo "  python3 ingest_neso_constraint_costs.py \\"
echo "    --data-dir ~/GB-Power-Market-JJ/neso_downloads/constraint_costs \\"
echo "    --test"
echo ""
echo "Production ingestion:"
echo "  python3 ingest_neso_constraint_costs.py \\"
echo "    --data-dir ~/GB-Power-Market-JJ/neso_downloads/constraint_costs"
echo ""
echo "======================================================================"
echo "TODO 4: FPN Ingestion (STARTED)"
echo "======================================================================"
echo "✅ Script ready: ingest_fpn_historical.py"
echo "🔄 Testing Oct 2024 (7 days)..."
echo ""
echo "Check test progress:"
echo "  tail -f logs/fpn_ingestion_oct_2024.log"
echo ""
echo "After test succeeds, run full 2024:"
echo "  python3 ingest_fpn_historical.py \\"
echo "    --start-date 2024-01-01 \\"
echo "    --end-date 2024-12-31"
echo ""
echo "======================================================================"
echo "TODO 5: Configure Interconnector URLs (MANUAL - 1-2 hours)"
echo "======================================================================"
echo "⚠️  Manual URL research required"
echo ""
echo "Steps:"
echo "  1. Visit: https://data.nationalgrideso.com/interconnectors/"
echo "  2. For each interconnector (IFA, IFA2, BritNed, NemoLink, NSL, Viking, ElecLink):"
echo "     - Click dataset name"
echo "     - Find 'Download' link"
echo "     - Copy resource ID from URL"
echo "  3. Update INTERCONNECTOR_URLS in ingest_interconnector_flows.py"
echo ""
echo "======================================================================"
echo "TODO 6: Ingest Interconnectors (AFTER TODO 5)"
echo "======================================================================"
echo "✅ Script ready: ingest_interconnector_flows.py"
echo ""
echo "After URLs configured, run:"
echo "  python3 ingest_interconnector_flows.py \\"
echo "    --start-year 2022 \\"
echo "    --end-year 2025"
echo ""
echo "======================================================================"
echo "Next Actions (Priority Order)"
echo "======================================================================"
echo "1. START NOW: Open browser, download NESO data (Todo 2, 3-4 hours)"
echo "2. WAIT: FPN test to complete (~7 min, check logs)"
echo "3. THEN: Run full FPN 2024 ingestion (~6 min)"
echo "4. PARALLEL: Research interconnector URLs (Todo 5, 1-2 hours)"
echo "5. THEN: Ingest interconnectors (Todo 6, 30 min)"
echo "6. MONITOR: P114 backfill (check daily)"
echo ""
echo "======================================================================"
echo "Estimated Timeline"
echo "======================================================================"
echo "Todo 1 (P114): 3-10 days (autonomous)"
echo "Todo 2-3 (NESO): 3-4 hours manual + 15 min ingestion"
echo "Todo 4 (FPN): 15 min total (test + production)"
echo "Todo 5-6 (Interconnectors): 1-2 hours research + 30 min ingestion"
echo ""
echo "Total hands-on time: 5-7 hours"
echo "Total calendar time: 5-10 days (waiting for P114)"
echo ""
