#!/usr/bin/env python3
"""
Setup Google Apps Script Menu for Sheet Refresh
This script helps you set up the custom menu in Google Sheets
"""

print("=" * 80)
print("🔧 SETUP: GOOGLE SHEETS REFRESH MENU")
print("=" * 80)
print()

SPREADSHEET_ID = '1-u794iGngn5_Ql_XocKSwvHSKWABWO0bVsudkUJAFqA'

print("This will add a custom menu to your Google Sheet that allows you to")
print("refresh data with a single click - no need to run Python manually!")
print()
print("=" * 80)
print("STEP 1: INSTALL GOOGLE APPS SCRIPT")
print("=" * 80)
print()
print("1. Open your Google Sheet:")
print(f"   https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}/")
print()
print("2. Click: Extensions > Apps Script")
print()
print("3. Delete any existing code in the editor")
print()
print("4. Copy the code from: google_sheets_menu.gs")
print("   (The file is in your project directory)")
print()
print("5. Paste it into the Apps Script editor")
print()
print("6. Click the Save icon (💾) or press Cmd+S / Ctrl+S")
print()
print("7. Name the project: 'Power Market Refresh Menu'")
print()
print("8. Close the Apps Script tab")
print()
print("9. Refresh your Google Sheet")
print()
print("10. You should now see a new menu: '⚡ Power Market'")
print()
print("=" * 80)
print("STEP 2: START THE WATCHER")
print("=" * 80)
print()
print("The watcher script monitors your sheet for refresh requests")
print("from the menu and automatically runs the Python update script.")
print()
print("In a NEW terminal window, run:")
print()
print("  cd ~/GB\\ Power\\ Market\\ JJ")
print("  python3 watch_sheet_for_refresh.py")
print()
print("Leave this running in the background!")
print()
print("💡 TIP: Use screen or tmux to keep it running:")
print()
print("  screen -S sheet-watcher")
print("  cd ~/GB\\ Power\\ Market\\ JJ")
print("  python3 watch_sheet_for_refresh.py")
print("  # Press Ctrl+A then D to detach")
print("  # Reconnect with: screen -r sheet-watcher")
print()
print("=" * 80)
print("STEP 3: TEST IT!")
print("=" * 80)
print()
print("1. Open your Google Sheet")
print()
print("2. Click the menu: ⚡ Power Market > 🔄 Refresh Data Now")
print()
print("3. You'll see a dialog: 'Refresh Requested'")
print()
print("4. Cell L5 will show: ⏳ Refreshing...")
print()
print("5. Watch the watcher terminal - you'll see it detect the request")
print("   and run the update script")
print()
print("6. After 30-60 seconds, cell L5 will show: ✅ Up to date")
print()
print("7. Refresh your browser to see the updated data!")
print()
print("=" * 80)
print("FEATURES")
print("=" * 80)
print()
print("Your new menu has these options:")
print()
print("  🔄 Refresh Data Now")
print("     - Triggers immediate refresh with current date range")
print()
print("  📊 Quick Refresh (1 Week)")
print("     - Sets date range to 1 Week AND refreshes")
print()
print("  📊 Quick Refresh (1 Month)")
print("     - Sets date range to 1 Month AND refreshes")
print()
print("  ℹ️ Help")
print("     - Shows help dialog in the sheet")
print()
print("=" * 80)
print("TROUBLESHOOTING")
print("=" * 80)
print()
print("Q: Menu doesn't appear after installing Apps Script")
print("A: Try these:")
print("   - Refresh the sheet (Cmd+R / Ctrl+R)")
print("   - Close and reopen the sheet")
print("   - Check Apps Script saved successfully")
print()
print("Q: Click 'Refresh Data Now' but nothing happens")
print("A: Check watcher is running:")
print("   - Look for terminal with 'WATCHING SHEET FOR REFRESH REQUESTS'")
print("   - If not running: python3 watch_sheet_for_refresh.py")
print()
print("Q: Status stays on '⏳ Refreshing...' forever")
print("A: Check watcher terminal for errors:")
print("   - May be BigQuery error")
print("   - May be authentication issue")
print("   - Check watcher output for error messages")
print()
print("Q: Status shows '❌ Error'")
print("A: Check watcher terminal output for details")
print("   Run update script manually to see full error:")
print("   python3 update_analysis_bi_enhanced.py")
print()
print("=" * 80)
print("FILES")
print("=" * 80)
print()
print("  google_sheets_menu.gs")
print("    - Google Apps Script code (paste into Apps Script editor)")
print()
print("  watch_sheet_for_refresh.py")
print("    - Python watcher script (run in terminal)")
print()
print("  update_analysis_bi_enhanced.py")
print("    - Data refresh script (called automatically by watcher)")
print()
print("=" * 80)
print("READY TO START!")
print("=" * 80)
print()
print("Next steps:")
print("  1. Install Apps Script (see STEP 1 above)")
print("  2. Start watcher: python3 watch_sheet_for_refresh.py")
print("  3. Test the menu!")
print()
