#!/usr/bin/env python3
"""
Google Search API Setup Script
=============================

This script helps you set up Google Custom Search API integration
with your existing jibber_jabber_key.json service account.

Steps performed:
1. Validates service account credentials
2. Checks Google Cloud API permissions
3. Guides you through Custom Search Engine setup
4. Creates environment configuration
5. Tests search functionality
"""

import json
import os
from pathlib import Path

from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError


def check_service_account():
    """Check if service account file exists and is valid."""
    key_file = Path("jibber_jabber_key.json")

    if not key_file.exists():
        print("❌ Service account file 'jibber_jabber_key.json' not found")
        print("   Please ensure your service account key is in the current directory")
        return False

    try:
        with open(key_file) as f:
            key_data = json.load(f)

        required_fields = [
            "type",
            "project_id",
            "private_key_id",
            "private_key",
            "client_email",
        ]
        missing_fields = [field for field in required_fields if field not in key_data]

        if missing_fields:
            print(f"❌ Service account file missing required fields: {missing_fields}")
            return False

        print(f"✅ Service account file is valid")
        print(f"   Project ID: {key_data['project_id']}")
        print(f"   Client Email: {key_data['client_email']}")
        return True

    except json.JSONDecodeError:
        print("❌ Service account file is not valid JSON")
        return False
    except Exception as e:
        print(f"❌ Error reading service account file: {e}")
        return False


def check_api_access():
    """Check if the service account has access to Custom Search API."""
    try:
        credentials = service_account.Credentials.from_service_account_file(
            "jibber_jabber_key.json", scopes=["https://www.googleapis.com/auth/cse"]
        )

        service = build("customsearch", "v1", credentials=credentials)
        print("✅ Successfully authenticated with Custom Search API")
        return True

    except Exception as e:
        print(f"❌ Failed to access Custom Search API: {e}")
        print("\n🔧 To fix this:")
        print("   1. Go to Google Cloud Console")
        print("   2. Enable Custom Search API for your project")
        print("   3. Ensure service account has appropriate permissions")
        return False


def guide_custom_search_setup():
    """Guide user through Custom Search Engine setup."""
    print("\n🔍 Custom Search Engine Setup Required")
    print("=" * 50)
    print("\n📋 Follow these steps:")
    print("1. Go to: https://cse.google.com/")
    print("2. Click 'Add' to create a new search engine")
    print("3. Configure your search engine:")
    print("   • Sites to search: *.gov.uk, *.ac.uk, or * (for all sites)")
    print("   • Language: English")
    print("   • Name: 'Jibber Jabber Energy Search'")
    print("4. Click 'Create'")
    print("5. In the control panel, go to 'Setup' > 'Basics'")
    print("6. Copy your 'Search engine ID'")

    search_engine_id = input("\n🔑 Paste your Search Engine ID here: ").strip()

    if not search_engine_id:
        print("❌ No Search Engine ID provided")
        return None

    print(f"✅ Search Engine ID saved: {search_engine_id}")
    return search_engine_id


def create_env_file(search_engine_id: str):
    """Create environment configuration file."""
    env_content = f"""# Google Search API Configuration
# Generated by setup_google_search.py

# Your Custom Search Engine ID
GOOGLE_SEARCH_ENGINE_ID="{search_engine_id}"

# Optional: API Key (if not using service account)
# GOOGLE_API_KEY="your_api_key_here"

# Service Account Configuration (already using jibber_jabber_key.json)
GOOGLE_APPLICATION_CREDENTIALS="jibber_jabber_key.json"

# BigQuery Integration
GOOGLE_CLOUD_PROJECT="jibber-jabber-knowledge"
"""

    with open(".env.search", "w") as f:
        f.write(env_content)

    print("✅ Created .env.search configuration file")
    print("   Add this to your shell: source .env.search")


def test_search(search_engine_id: str):
    """Test the search functionality."""
    print("\n🧪 Testing search functionality...")

    try:
        os.environ["GOOGLE_SEARCH_ENGINE_ID"] = search_engine_id

        # Import our search API
        from google_search_api import GoogleSearchAPI

        search_api = GoogleSearchAPI()

        # Test search
        results = search_api.search(
            query="renewable energy UK", num_results=3, search_type="web"
        )

        print(f"✅ Search test successful!")
        print(f"   Query: 'renewable energy UK'")
        print(f"   Results found: {len(results.get('items', []))}")
        print(f"   Total results: {results.get('total_results', 0):,}")

        if results.get("items"):
            print("\n📋 Sample results:")
            for i, item in enumerate(results["items"][:2], 1):
                print(f"   {i}. {item['title']}")
                print(f"      {item['link']}")

        return True

    except Exception as e:
        print(f"❌ Search test failed: {e}")
        return False


def main():
    """Main setup process."""
    print("🚀 Google Search API Setup")
    print("=" * 40)

    # Step 1: Check service account
    if not check_service_account():
        return

    print()

    # Step 2: Check API access
    if not check_api_access():
        return

    # Step 3: Get search engine ID
    search_engine_id = os.getenv("GOOGLE_SEARCH_ENGINE_ID")

    if not search_engine_id:
        search_engine_id = guide_custom_search_setup()
        if not search_engine_id:
            return
    else:
        print(f"✅ Using existing Search Engine ID: {search_engine_id}")

    # Step 4: Create environment file
    create_env_file(search_engine_id)

    # Step 5: Test functionality
    if test_search(search_engine_id):
        print("\n🎉 Google Search API setup complete!")
        print("\n📚 Next steps:")
        print("   1. Run: source .env.search")
        print("   2. Use: python google_search_api.py")
        print("   3. Integrate with your existing data pipeline")

        print("\n💡 Usage examples:")
        print("   • Search energy news")
        print("   • Find government documents")
        print("   • Research energy companies")
        print("   • Integrate with BMRS data analysis")
    else:
        print("\n❌ Setup incomplete - please fix errors above")


if __name__ == "__main__":
    main()
