#!/bin/bash
# Manual Apps Script Deployment Guide
# Use this if clasp authentication fails

echo "📝 Manual Apps Script Deployment"
echo "=================================="
echo ""
echo "Since clasp authentication is having issues, deploy manually:"
echo ""
echo "1. Open Google Sheets:"
echo "   https://docs.google.com/spreadsheets/d/1-u794iGngn5_Ql_XocKSwvHSKWABWO0bVsudkUJAFqA/"
echo ""
echo "2. Go to: Extensions → Apps Script"
echo ""
echo "3. In the Apps Script editor:"
echo "   - Delete any existing code"
echo "   - Copy the code below (or from Code.gs)"
echo "   - Paste into the editor"
echo "   - Save (Ctrl+S or File → Save)"
echo ""
echo "4. Refresh Google Sheets page (Ctrl+R)"
echo ""
echo "5. Test: Look for '⚡ GB Energy Dashboard' menu in toolbar"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Code to copy (also in Code.gs):"
echo ""

cat /home/george/GB-Power-Market-JJ/apps_script_deploy/Code.gs

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ After deployment:"
echo "   - Menu should appear: '⚡ GB Energy Dashboard'"
echo "   - Go to BESS sheet"
echo "   - Click menu → 'Format Enhanced Section'"
echo "   - Rows 58-60+ should be formatted with colors"
echo ""
echo "🔧 Existing sections preserved:"
echo "   - Rows 1-14: DNO Lookup ✅"
echo "   - Rows 15-20: HH Profile ✅"
echo "   - Rows 27-50: BtM PPA ✅"
echo ""
