#!/bin/bash
# Fix Apps Script Deployment - Deploy to CORRECT Sheet

echo "🔧 BESS Apps Script - Redeployment to Correct Sheet"
echo "===================================================="
echo ""
echo "✅ FIXED: Code.gs now references correct sheet (12jY0d4j...)"
echo ""
echo "📋 Current Status:"
echo "   ❌ Apps Script deployed to WRONG sheet (1LmMq4OE... V2 sheet)"
echo "   ✅ Python pipeline updates CORRECT sheet (12jY0d4j... Main sheet)"
echo "   ✅ Code files now fixed with correct sheet ID"
echo ""
echo "🎯 NEXT STEPS:"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 1: Get Script ID from Correct Sheet"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Open the CORRECT sheet:"
echo "   https://docs.google.com/spreadsheets/d/12jY0d4jzD6lXFOVoqZZNjPRN-hJE3VmWFAPcC_kPKF8/"
echo ""
echo "2. Go to: Extensions → Apps Script"
echo ""
echo "3. Check if Apps Script project exists:"
echo ""
echo "   Option A - If script EXISTS:"
echo "      • Look at browser URL bar"
echo "      • Copy the long ID after '/d/' and before '/edit'"
echo "      • Example: https://script.google.com/...d/SCRIPT_ID_HERE/edit"
echo "      • Save this Script ID"
echo ""
echo "   Option B - If NO script or OLD script:"
echo "      • Delete old code (if any)"
echo "      • Leave editor open"
echo "      • Continue to Step 2"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 2: Deploy Fixed Code"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Method A: MANUAL DEPLOYMENT (Recommended - Always Works)"
echo "--------------------------------------------------------"
echo "1. In Apps Script editor (from Step 1)"
echo "2. Delete all existing code"
echo "3. Copy contents from:"
echo "   /home/george/GB-Power-Market-JJ/apps_script_deploy/Code.gs"
echo "4. Paste into editor"
echo "5. Click Save (Ctrl+S)"
echo "6. Refresh Google Sheets page"
echo "7. Look for '⚡ GB Energy Dashboard' menu"
echo ""
echo "Method B: CLASP DEPLOYMENT (If you have Script ID)"
echo "--------------------------------------------------------"
echo "1. Update .clasp.json with Script ID from Step 1:"
echo ""
echo "   cat > /home/george/GB-Power-Market-JJ/apps_script_deploy/.clasp.json << EOF"
echo "   {"
echo "     \"scriptId\": \"YOUR_SCRIPT_ID_HERE\","
echo "     \"rootDir\": \"/home/george/GB-Power-Market-JJ/apps_script_deploy\""
echo "   }"
echo "   EOF"
echo ""
echo "2. Authenticate clasp (if not done):"
echo "   cd /home/george/GB-Power-Market-JJ/apps_script_deploy"
echo "   clasp login --no-localhost"
echo ""
echo "3. Deploy:"
echo "   clasp push"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 3: Verify Deployment"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. Open correct sheet:"
echo "   https://docs.google.com/spreadsheets/d/12jY0d4jzD6lXFOVoqZZNjPRN-hJE3VmWFAPcC_kPKF8/"
echo ""
echo "2. Refresh page (Ctrl+R)"
echo ""
echo "3. Check for menu: '⚡ GB Energy Dashboard'"
echo ""
echo "4. Go to BESS sheet"
echo ""
echo "5. Verify existing data INTACT:"
echo "   ✅ Rows 1-14: DNO Lookup (postcode/MPAN)"
echo "   ✅ Rows 15-20: HH Profile (500/1000/1500 kW)"
echo "   ✅ Rows 27-50: BtM PPA Analysis"
echo ""
echo "6. Test formatting:"
echo "   • Click menu → '🎨 Format BESS Enhanced'"
echo "   • Check rows 58-60 formatted correctly"
echo "   • Check KPIs panel (T60:U67) orange/yellow"
echo "   • Check Revenue stack (W60:Y67) orange/yellow"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 4: Test Python Pipeline"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Run pipeline to verify it still updates correct sheet:"
echo ""
echo "   cd /home/george/GB-Power-Market-JJ"
echo "   python3 dashboard_pipeline.py"
echo ""
echo "Expected: Updates Dashboard sheet and BESS enhanced section"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📄 Files Fixed:"
echo "   ✅ apps_script_enhanced/bess_integration.gs (line 7)"
echo "   ✅ apps_script_deploy/Code.gs (line 7)"
echo ""
echo "📊 Sheet IDs:"
echo "   ❌ OLD (V2):  1LmMq4OEE639Y-XXpOJ3xnvpAmHB6vUovh5g6gaU_vzc"
echo "   ✅ NEW (Main): 12jY0d4jzD6lXFOVoqZZNjPRN-hJE3VmWFAPcC_kPKF8"
echo ""
echo "📖 Full diagnostic: DIAGNOSTIC_REPORT.md"
echo ""
